type="Post"
name="final_fantasy_crystal_chronicles"
year="2003"
description="Final Fantasy Crystal Chronicles"
parents = ["jrpg", "square", "non_linear", "gamecube", "akitoshi_kawazu", "videogame"]
image = "https://d2w9rnfcy7mm78.cloudfront.net/733484/original_3cf242e4e27bec3396ef1f97266d156f.jpg?1476243339"
dl_url = "url.org/#64zx79sYfq2TD82vTexI19DKua4Ns8YXMHBYWkrsCMpUZRaj1QLAUjKxIApEE1cQGt8wviSh8pH58N623HviJiFq7T4oFlOZCMov"

---
**Star Control: Famous Battles of the Ur-Quan Conflict Volume IV** was developed by Fred Ford and Paul Reiche III. It was released for the PC in 1990 and (in a somewhat cut-down form, and called simply Star Control) for the Commodore 64 in 1991 by Accolade.

A port for the Sega Genesis was released by Ballistic in that same year. The DOS version is available from Good Old Games.
